# GitHub Pages Configuration
# This file enables GitHub Pages for private repositories

# Build settings (if using Jekyll - optional)
plugins:
  - jekyll-relative-links

# Relative links configuration
relative_links:
  enabled: true
  collections: true

# Exclude files from the site
exclude:
  - README.md
  - .gitignore
  - .git/
