# Netlify configuration file
# This optimizes your site for better performance and SEO

[build]
  # Build settings
  publish = "."
  
[build.environment]
  # Ensure public access
  NODE_VERSION = "18"

[[headers]]
  # Cache static assets
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Access-Control-Allow-Origin = "*"
    
[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=300"
    Access-Control-Allow-Origin = "*"

# Redirect rules for clean URLs
[[redirects]]
  from = "/roadmaps"
  to = "/roadmaps.html"
  status = 200

[[redirects]]
  from = "/components"
  to = "/component-detail.html"
  status = 200
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  # Security headers for all pages
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Redirect rules
[[redirects]]
  from = "/home"
  to = "/"
  status = 301

# Form handling (if you add contact forms later)
[build.environment]
  NODE_VERSION = "18"
